name: Convert TODOs to Github Issues

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  todo:
    runs-on: ubuntu
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: alstr/todo-to-issue-action@v5
        with:
          AUTO_P: false
